[build]
#build-std = true
default-target = "aarch64-unknown-linux-gnu"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update && apt --assume-yes install libdbus-1-dev:$CROSS_DEB_ARCH"
]
